### ISSUE TITLE
After typing in Docker-Compose up, the docker keeps going like this! Please help me!

### ISSUE THREAD

**Issue by yrregnehc** [ZJGSU-Open-Source/docker-oj#3]
![image](https://user-images.githubusercontent.com/29784649/27710562-2eaf7b68-5cee-11e7-9668-7ea41f57cdc6.png)

**Comment by clarkzjw** [comment]
It's normal because you are using `docker-compose up`. If you do not want to see logs, you can use `docker-compose up -d` to let it run in the background.

You can refer to `docker-compose` docs here: https://docs.docker.com/compose/reference/up/
