### ISSUE TITLE
If I'm using Windows and I got the docker running, how can I see the website? Because 127.0.0.1:8080 doesn't work on my Windows platform

### ISSUE THREAD

**Issue by yrregnehc** [ZJGSU-Open-Source/docker-oj#4]

**Comment by clarkzjw** [comment]
Well, we haven't tested on Windows. Please list more info:

+ Windows version:
+ Your docker version:
+ How do you run docker on Windows: [`docker for windows`](https://www.docker.com/docker-windows) or [`docker toolbox`](https://www.docker.com/products/docker-toolbox)
